import {
  PERIODOS_PREFERIDOS,
  STATUS_DO_AGENDAMENTO,
  TIPOS_DE_EXAME,
} from "../dominio/tipos-do-agendamento";
import type {
  AgendamentoParaPainel,
  ColaboradorParaSelecao,
} from "./tipos-do-painel";

export const COLABORADORES_DE_DEMONSTRACAO: ColaboradorParaSelecao[] = [
  {
    id: "colaborador-ana",
    nome: "Ana Torres",
    cpfMascarado: "***.***.***-42",
    matricula: "GH-1042",
    cargo: "Analista financeira",
    iniciais: "AT",
    cor: "verde",
  },
  {
    id: "colaborador-bruno",
    nome: "Bruno Lima",
    cpfMascarado: "***.***.***-17",
    matricula: "GH-0987",
    cargo: "Técnico de manutenção",
    iniciais: "BL",
    cor: "azul",
  },
  {
    id: "colaborador-camila",
    nome: "Camila Souza",
    cpfMascarado: "***.***.***-05",
    matricula: "GH-0881",
    cargo: "Supervisora de operações",
    iniciais: "CS",
    cor: "lilas",
  },
  {
    id: "colaborador-diego",
    nome: "Diego Alves",
    cpfMascarado: "***.***.***-63",
    matricula: "GH-0744",
    cargo: "Operador de produção",
    iniciais: "DA",
    cor: "laranja",
  },
  {
    id: "colaborador-elisa",
    nome: "Elisa Nunes",
    cpfMascarado: "***.***.***-29",
    matricula: "GH-1120",
    cargo: "Assistente administrativa",
    iniciais: "EN",
    cor: "rosa",
  },
];

export const AGENDAMENTOS_DE_DEMONSTRACAO: AgendamentoParaPainel[] = [
  {
    id: "agendamento-ana",
    empresaId: "empresa-horizonte",
    clinicaId: "clinica-bem-viver",
    colaboradorId: "colaborador-ana",
    colaborador: COLABORADORES_DE_DEMONSTRACAO[0],
    empresaNome: "Grupo Horizonte",
    clinicaNome: "Clínica Bem Viver",
    recursoDaClinicaNome: null,
    tipoDeExame: TIPOS_DE_EXAME.ADMISSIONAL,
    status: STATUS_DO_AGENDAMENTO.SOLICITADO,
    dataDeReferencia: "2026-08-08",
    dataLimite: "2026-08-08",
    periodoPreferido: PERIODOS_PREFERIDOS.MANHA,
    diasDeAfastamento: null,
    observacoes: "Admissão prevista para o turno da manhã.",
    recursoDaClinicaId: null,
    inicioAgendado: null,
    fimAgendado: null,
    motivoDoCancelamento: null,
    criadoPor: "usuario-rh",
    criadoEm: "2026-08-04T13:20:00.000Z",
    atualizadoEm: "2026-08-04T13:20:00.000Z",
    realizadoEm: null,
  },
  {
    id: "agendamento-bruno",
    empresaId: "empresa-horizonte",
    clinicaId: "clinica-bem-viver",
    colaboradorId: "colaborador-bruno",
    colaborador: COLABORADORES_DE_DEMONSTRACAO[1],
    empresaNome: "Grupo Horizonte",
    clinicaNome: "Clínica Bem Viver",
    recursoDaClinicaNome: "Medicina do Trabalho",
    tipoDeExame: TIPOS_DE_EXAME.PERIODICO,
    status: STATUS_DO_AGENDAMENTO.AGENDADO,
    dataDeReferencia: "2026-08-12",
    dataLimite: "2026-08-12",
    periodoPreferido: PERIODOS_PREFERIDOS.QUALQUER,
    diasDeAfastamento: null,
    observacoes: null,
    recursoDaClinicaId: "agenda-medicina",
    inicioAgendado: "2026-08-07T09:00:00-03:00",
    fimAgendado: "2026-08-07T09:30:00-03:00",
    motivoDoCancelamento: null,
    criadoPor: "usuario-rh",
    criadoEm: "2026-08-01T10:10:00.000Z",
    atualizadoEm: "2026-08-02T14:30:00.000Z",
    realizadoEm: null,
  },
  {
    id: "agendamento-camila",
    empresaId: "empresa-horizonte",
    clinicaId: "clinica-bem-viver",
    colaboradorId: "colaborador-camila",
    colaborador: COLABORADORES_DE_DEMONSTRACAO[2],
    empresaNome: "Grupo Horizonte",
    clinicaNome: "Clínica Bem Viver",
    recursoDaClinicaNome: "Medicina do Trabalho",
    tipoDeExame: TIPOS_DE_EXAME.RETORNO_AO_TRABALHO,
    status: STATUS_DO_AGENDAMENTO.AGENDADO,
    dataDeReferencia: "2026-08-06",
    dataLimite: "2026-08-06",
    periodoPreferido: PERIODOS_PREFERIDOS.MANHA,
    diasDeAfastamento: 41,
    observacoes: "Retorno gradual será avaliado durante o exame.",
    recursoDaClinicaId: "agenda-medicina",
    inicioAgendado: "2026-08-06T08:00:00-03:00",
    fimAgendado: "2026-08-06T08:30:00-03:00",
    motivoDoCancelamento: null,
    criadoPor: "usuario-rh",
    criadoEm: "2026-08-03T11:00:00.000Z",
    atualizadoEm: "2026-08-03T15:10:00.000Z",
    realizadoEm: null,
  },
  {
    id: "agendamento-diego",
    empresaId: "empresa-horizonte",
    clinicaId: "clinica-bem-viver",
    colaboradorId: "colaborador-diego",
    colaborador: COLABORADORES_DE_DEMONSTRACAO[3],
    empresaNome: "Grupo Horizonte",
    clinicaNome: "Clínica Bem Viver",
    recursoDaClinicaNome: "Medicina do Trabalho",
    tipoDeExame: TIPOS_DE_EXAME.PERIODICO,
    status: STATUS_DO_AGENDAMENTO.REALIZADO,
    dataDeReferencia: "2026-08-04",
    dataLimite: "2026-08-04",
    periodoPreferido: PERIODOS_PREFERIDOS.TARDE,
    diasDeAfastamento: null,
    observacoes: null,
    recursoDaClinicaId: "agenda-medicina",
    inicioAgendado: "2026-08-04T14:00:00-03:00",
    fimAgendado: "2026-08-04T14:30:00-03:00",
    motivoDoCancelamento: null,
    criadoPor: "usuario-rh",
    criadoEm: "2026-07-28T12:00:00.000Z",
    atualizadoEm: "2026-08-04T17:35:00.000Z",
    realizadoEm: "2026-08-04T17:35:00.000Z",
  },
  {
    id: "agendamento-elisa",
    empresaId: "empresa-horizonte",
    clinicaId: "clinica-bem-viver",
    colaboradorId: "colaborador-elisa",
    colaborador: COLABORADORES_DE_DEMONSTRACAO[4],
    empresaNome: "Grupo Horizonte",
    clinicaNome: "Clínica Bem Viver",
    recursoDaClinicaNome: "Medicina do Trabalho",
    tipoDeExame: TIPOS_DE_EXAME.MUDANCA_DE_RISCO,
    status: STATUS_DO_AGENDAMENTO.NAO_COMPARECEU,
    dataDeReferencia: "2026-08-03",
    dataLimite: "2026-08-03",
    periodoPreferido: PERIODOS_PREFERIDOS.TARDE,
    diasDeAfastamento: null,
    observacoes: "Mudança para área com novo perfil de risco.",
    recursoDaClinicaId: "agenda-medicina",
    inicioAgendado: "2026-08-03T15:00:00-03:00",
    fimAgendado: "2026-08-03T15:30:00-03:00",
    motivoDoCancelamento: null,
    criadoPor: "usuario-rh",
    criadoEm: "2026-07-29T09:00:00.000Z",
    atualizadoEm: "2026-08-03T17:00:00.000Z",
    realizadoEm: null,
  },
];
